/**
 * Copyright (c) 2014-2016 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.openhab.binding.zwave.internal.protocol.commandclass.impl;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Class to implement the Z-Wave command class <b>COMMAND_CLASS_NETWORK_MANAGEMENT_PROXY</b> version <b>2</b>.<br>
 *
 * Command Class Network Management Proxy<br>
 *
 * This class provides static methods for processing received messages (message handler) and
 * methods to get a message to send on the Z-Wave network.<br>
 *
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class CommandClassNetworkManagementProxyV2 {
    private static final Logger logger = LoggerFactory.getLogger(CommandClassNetworkManagementProxyV2.class);

    /**
     * Integer command class key for COMMAND_CLASS_NETWORK_MANAGEMENT_PROXY
     */
    public final static int COMMAND_CLASS_KEY = 0x52;

    /**
     * Node Info Cached Get Command Constant
     */
    public final static int NODE_INFO_CACHED_GET = 0x03;
    /**
     * Node Info Cached Report Command Constant
     */
    public final static int NODE_INFO_CACHED_REPORT = 0x04;
    /**
     * Node List Get Command Constant
     */
    public final static int NODE_LIST_GET = 0x01;
    /**
     * Node List Report Command Constant
     */
    public final static int NODE_LIST_REPORT = 0x02;

    /**
     * Creates a new message with the NODE_INFO_CACHED_GET command.<br>
     *
     * Node Info Cached Get<br>
     *
     *
     * @param seqNo {@link Integer}
     * @param maxAge {@link Integer}
     * @param nodeId {@link Integer}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getNodeInfoCachedGet(Integer seqNo, Integer maxAge, Integer nodeId) {
        logger.debug("Creating command message NODE_INFO_CACHED_GET version 2");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(NODE_INFO_CACHED_GET);

        // Process 'Seq. No'
        outputData.write(seqNo);

        // Process 'Properties1'
        outputData.write(maxAge & 0x0F);

        // Process 'Node ID'
        // Check the node number boundary
        if (nodeId < 1 || nodeId > 232) {
            logger.debug("Node number is out of bounds {}", nodeId);
            return null;
        }
        outputData.write(nodeId);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the NODE_INFO_CACHED_GET command<br>
     *
     * Node Info Cached Get<br>
     *
     *
     * The output data has the following structure<br>
     *
     * <ul>
     * <li>SEQ_NO {@link Integer}
     * <li>MAX_AGE {@link Integer}
     * <li>NODE_ID {@link Integer}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleNodeInfoCachedGet(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Process 'Seq. No'
        response.put("SEQ_NO", new Integer(payload[4]));

        // Process 'Properties1'
        response.put("MAX_AGE", new Integer(payload[5] & 0x0F));

        // Process 'Node ID'
        response.put("NODE_ID", new Integer(payload[6]));

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the NODE_INFO_CACHED_REPORT command.<br>
     *
     * Node Info Cached Report<br>
     *
     *
     * @param seqNo {@link Integer}
     * @param age {@link Integer}
     * @param status {@link String}
     * @param capability {@link Integer}
     * @param listening {@link Boolean}
     * @param security {@link Integer}
     * @param sensor {@link Integer}
     * @param opt {@link Boolean}
     * @param grantedKeys {@link Integer}
     * @param basicDeviceClass {@link Integer}
     * @param genericDeviceClass {@link Integer}
     * @param specificDeviceClass {@link Integer}
     * @param nonSecureCommandClass {@link List<Integer>}
     * @param secureCommandClass {@link List<Integer>}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getNodeInfoCachedReport(Integer seqNo, Integer age, String status, Integer capability,
            Boolean listening, Integer security, Integer sensor, Boolean opt, Integer grantedKeys,
            Integer basicDeviceClass, Integer genericDeviceClass, Integer specificDeviceClass,
            List<Integer> nonSecureCommandClass, List<Integer> secureCommandClass) {
        logger.debug("Creating command message NODE_INFO_CACHED_REPORT version 2");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(NODE_INFO_CACHED_REPORT);

        // Process 'Seq. No'
        outputData.write(seqNo);

        // Process 'Properties1'
        int valProperties1 = 0;
        valProperties1 |= age & 0x0F;
        int valstatus;
        switch (status) {
            case "STATUS_OK":
                valstatus = 0;
                break;
            case "STATUS_NOT_RESPONDING":
                valstatus = 1;
                break;
            case "STATUS_UNKNOWN":
                valstatus = 2;
                break;
            default:
                throw new IllegalArgumentException("Unknown enum value for status: " + status);
        }
        valProperties1 |= valstatus >> 4 & 0xF0;
        outputData.write(valProperties1);

        // Process 'Properties2'
        int valProperties2 = 0;
        valProperties2 |= capability & 0x7F;
        valProperties2 |= listening ? 0x80 : 0;
        outputData.write(valProperties2);

        // Process 'Properties3'
        int valProperties3 = 0;
        valProperties3 |= security & 0x0F;
        valProperties3 |= ((sensor << 4) & 0x70);
        valProperties3 |= opt ? 0x80 : 0;
        outputData.write(valProperties3);

        // Process 'Granted Keys'
        outputData.write(grantedKeys);

        // Process 'Basic Device Class'
        outputData.write(basicDeviceClass);

        // Process 'Generic Device Class'
        outputData.write(genericDeviceClass);

        // Process 'Specific Device Class'
        outputData.write(specificDeviceClass);

        // Process 'Non-Secure Command Class'

        // Process 'Security MARK'

        // Process 'Secure Command Class'

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the NODE_INFO_CACHED_REPORT command<br>
     *
     * Node Info Cached Report<br>
     *
     *
     * The output data has the following structure<br>
     *
     * <ul>
     * <li>SEQ_NO {@link Integer}
     * <li>AGE {@link Integer}
     * <li>STATUS {@link String}
     * <li>CAPABILITY {@link Integer}
     * <li>LISTENING {@link Boolean}
     * <li>SECURITY {@link Integer}
     * <li>SENSOR {@link Integer}
     * <li>OPT {@link Boolean}
     * <li>GRANTED_KEYS {@link Integer}
     * <li>BASIC_DEVICE_CLASS {@link Integer}
     * <li>GENERIC_DEVICE_CLASS {@link Integer}
     * <li>SPECIFIC_DEVICE_CLASS {@link Integer}
     * <li>NON_SECURE_COMMAND_CLASS {@link List<Integer>}
     * <li>SECURE_COMMAND_CLASS {@link List<Integer>}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleNodeInfoCachedReport(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // We're using variable length fields, so track the offset
        int msgOffset = 2;

        // Process 'Seq. No'
        response.put("SEQ_NO", new Integer(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Properties1'
        response.put("AGE", new Integer(payload[msgOffset] & 0x0F));
        switch ((payload[msgOffset] & 0xF0) >> 4) {
            case 0x00:
                response.put("STATUS", "STATUS_OK");
                break;
            case 0x01:
                response.put("STATUS", "STATUS_NOT_RESPONDING");
                break;
            case 0x02:
                response.put("STATUS", "STATUS_UNKNOWN");
                break;
            default:
                logger.debug("Unknown enum value {} for STATUS", String.format("0x%02X", msgOffset));
        }
        msgOffset += 1;

        // Process 'Properties2'
        response.put("CAPABILITY", new Integer(payload[msgOffset] & 0x7F));
        response.put("LISTENING", new Boolean((payload[msgOffset] & 0x80) != 0));
        msgOffset += 1;

        // Process 'Properties3'
        response.put("SECURITY", new Integer(payload[msgOffset] & 0x0F));
        response.put("SENSOR", new Integer((payload[msgOffset] & 0x70 >> 4)));
        response.put("OPT", new Boolean((payload[msgOffset] & 0x80) != 0));
        msgOffset += 1;

        // Process 'Granted Keys'
        response.put("GRANTED_KEYS", new Integer(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Basic Device Class'
        response.put("BASIC_DEVICE_CLASS", new Integer(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Generic Device Class'
        response.put("GENERIC_DEVICE_CLASS", new Integer(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Specific Device Class'
        response.put("SPECIFIC_DEVICE_CLASS", new Integer(payload[msgOffset]));
        msgOffset += 1;

        // Process 'Non-Secure Command Class'
        List<Integer> valNonSecureCommandClass = new ArrayList<Integer>();
        while (msgOffset < payload.length) {
            // Detect the marker
            if ((payload[msgOffset] == 0xF1) && (payload[msgOffset + 1] == 0x00)) {
                break;
            }
            valNonSecureCommandClass.add((int) payload[msgOffset]);
            msgOffset++;
        }
        response.put("NON_SECURE_COMMAND_CLASS", valNonSecureCommandClass);

        // Process 'Security MARK'
        // Adjust position to account for the marker
        msgOffset += 2;

        // Process 'Secure Command Class'
        List<Integer> valSecureCommandClass = new ArrayList<Integer>();
        while (msgOffset < payload.length) {
            valSecureCommandClass.add((int) payload[msgOffset]);
            msgOffset++;
        }
        response.put("SECURE_COMMAND_CLASS", valSecureCommandClass);

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the NODE_LIST_GET command.<br>
     *
     * Node List Get<br>
     *
     *
     * @param seqNo {@link Integer}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getNodeListGet(Integer seqNo) {
        logger.debug("Creating command message NODE_LIST_GET version 2");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(NODE_LIST_GET);

        // Process 'Seq. No'
        outputData.write(seqNo);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the NODE_LIST_GET command<br>
     *
     * Node List Get<br>
     *
     *
     * The output data has the following structure<br>
     *
     * <ul>
     * <li>SEQ_NO {@link Integer}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleNodeListGet(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Process 'Seq. No'
        response.put("SEQ_NO", new Integer(payload[4]));

        // Return the map of processed response data;
        return response;
    }

    /**
     * Creates a new message with the NODE_LIST_REPORT command.<br>
     *
     * Node List Report<br>
     *
     *
     * @param seqNo {@link Integer}
     * @param status {@link Integer}
     * @param nodeListControllerId {@link Integer}
     * @param nodeListData {@link List<String>}
     * @return the {@link byte[]} array with the command to send
     */
    static public byte[] getNodeListReport(Integer seqNo, Integer status, Integer nodeListControllerId,
            List<String> nodeListData) {
        logger.debug("Creating command message NODE_LIST_REPORT version 2");

        ByteArrayOutputStream outputData = new ByteArrayOutputStream();
        outputData.write(COMMAND_CLASS_KEY);
        outputData.write(NODE_LIST_REPORT);

        // Process 'Seq. No'
        outputData.write(seqNo);

        // Process 'Status'
        outputData.write(status);

        // Process 'Node List Controller ID'
        outputData.write(nodeListControllerId);

        // Process 'Node List Data'
        int valNodeListData = 0;
        outputData.write(valNodeListData);

        return outputData.toByteArray();
    }

    /**
     * Processes a received frame with the NODE_LIST_REPORT command<br>
     *
     * Node List Report<br>
     *
     *
     * The output data has the following structure<br>
     *
     * <ul>
     * <li>SEQ_NO {@link Integer}
     * <li>STATUS {@link Integer}
     * <li>NODE_LIST_CONTROLLER_ID {@link Integer}
     * <li>NODE_LIST_DATA {@link List<String>}
     * </ul>
     *
     * @param payload the {@link byte[]} payload data to process
     * @return a {@link Map} of processed response data
     */
    public static Map<String, Object> handleNodeListReport(byte[] payload) {
        // Create our response map
        Map<String, Object> response = new HashMap<String, Object>();

        // Process 'Seq. No'
        response.put("SEQ_NO", new Integer(payload[4]));

        // Process 'Status'
        switch (payload[5]) {
            case 0x00:
                response.put("STATUS", "LATEST");
                break;
            case 0x01:
                response.put("STATUS", "MAY_NOT_BE_THE_LATEST");
                break;
            default:
                logger.debug("");
                break;
        }

        // Process 'Node List Controller ID'
        response.put("NODE_LIST_CONTROLLER_ID", new Integer(payload[6]));

        // Process 'Node List Data'
        List<String> responseNodeListData = new ArrayList<String>();
        int cntNodeListData = 0;
        while (cntNodeListData < payload.length - 7) {
            if ((payload[7 + (cntNodeListData / 8)] & cntNodeListData % 8) == 0) {
                continue;
            }
            responseNodeListData.add("NODE_LIST_DATA_" + cntNodeListData);
        }
        response.put("NODE_LIST_DATA", responseNodeListData);

        // Return the map of processed response data;
        return response;
    }

}
